- _sass/custom/custom.scss
- docs/reference/objects/biography.md
- docs/reference/objects/company.md
- docs/reference/objects/footer/footer_item.md
- docs/reference/objects/footer/index.md
- docs/reference/objects/image.md
- docs/reference/objects/menu/index.md
- docs/reference/objects/menu/menu_item.md
- docs/reference/objects/pagintation.md
- docs/reference/objects/product/accommodation.md
- docs/reference/objects/product/faq.md
- docs/reference/objects/product/highlight.md
- docs/reference/objects/product/host.md
- docs/reference/objects/product/index.md
- docs/reference/objects/product/promotion.md
- docs/reference/objects/product/schedule_element.md
- docs/reference/objects/product/testimonial.md
- docs/reference/objects/product/trip_tip.md
- docs/reference/objects/product/useful_info.md
- docs/reference/objects/product/variant.md
- docs/reference/objects/product/venue.md
- docs/reference/objects/product/whats_included.md
- docs/reference/objects/series.md
We fix any undefined links after pulling over from Gitbook using the {%
link %} tag, we also replace any code sections that were in Gitbook and
not pulled over whilst we're in here
> Fix links and code samples

- docs/reference/search/index.md
- docs/reference/tags/index.md
- docs/reference/tags/product_search/index.md
Search info wasn't added as part of the docs migration.
> Add missing search info

- docs/reference/objects/product/extra.md
- docs/reference/objects/product/variant.md
This is the documentation for the new `type` methods introduced in this Rails PR https://github.com/easolhq/easol/pull/6533.
> Add docs for new `type` methods on extra and variant

- docs/reference/objects/product/address.md
- docs/reference/objects/product/blog_post_section.md
- docs/reference/objects/product/faq.md
- docs/reference/objects/product/index.md
This PR also includes small tweaks to `address` and `faqs`.
This commits were on another branch that was deprecated but were left behind when we've migrated to the new `main` branch. This just bring them back without force pushing to `main`.
> Complete `blog_post_section` drop doc 

- docs/reference/filters/money/index.md
This adds initial documentation for filters focussing on the Money Filter first.
Want to sense check the examples in particular as this filter can be a bit confusing.
> Add docs for money filter

- docs/reference/objects/product/extra.md
- docs/reference/objects/product/modifier_group.md
- docs/reference/objects/product/variant/index.md
These new methods are being made available to support custom booking journeys that require pre-checkout modifications to extras and variants. (The previously available `modifier_groups` may display post-checkout options which will break the booking logic if used pre-checkout.)
> Add new `pre_checkout_modifier_groups` methods

- docs/reference/tags/easol_badge_tag/index.md
This commit adds documentation for the easol badge tag including an example of its liquid tag input and the rendered result.
> Documenting the Easol Badge Tag

- docs/reference/tags/currency_switcher_tag/index.md
This commit adds documentation for the Currency Switcher Tag including an example of its liquid tag input and the rendered result.
> Documenting the Currency Switcher Tag

- docs/reference/tags/cache_tag/index.md
This commit adds documentation for the Cache tag including an example of its liquid tag input, extra params and the rendered result.
> Documenting the Cache Tag

- docs/guides/best_practices/index.md
- docs/guides/cart_on_sites/index.md
- docs/guides/cart_shop/index.md
- docs/guides/customer_terms/index.md
- docs/guides/dependencies/index.md
- docs/guides/developer_tools/index.md
- docs/guides/filters/index.md
- docs/guides/getting_started/index.md
- docs/guides/internationalisation/index.md
- docs/guides/pricing_and_payments/index.md
- docs/guides/product_merchandising/index.md
- docs/guides/product_search/index.md
- docs/guides/seo/index.md
- docs/guides/site_navigation/index.md
- docs/guides/site_styles/index.md
- docs/guides/tags/index.md
- docs/guides/troubleshooting/index.md
Currently the nav on easol.dev orders alphabetically. This sets an explicit order for the nav items.
> Add nav order to docs

- docs/reference/tags/form_tags/create_line_item/create_line_item.md
This commit adds documentation for the Create Line Item tag, including liquid tag input examples and the rendered result.
PLEASE NOTE: The file (docs/reference/tags/create_line_item.md) will be moved and renamed when https://github.com/easolhq/easolhq.github.io/pull/57 has been merged.
> Documenting the Create Line Item Tag

- docs/reference/tags/form_tags/item_selections/item_selections.md
This commit adds documentation for the Item Selections Tag, including liquid tag input examples and the rendered result.
PLEASE NOTE: The file (docs/reference/tags/item_selections.md) will be moved and renamed when [this link](https://github.com/easolhq/easolhq.github.io/pull/57) has been merged.
> Documenting the Item Selections Tag

- docs/reference/filters/group_by.md
- docs/reference/filters/money.md
- docs/reference/filters/pagination.md
- docs/reference/filters/parameterize.md
- docs/reference/filters/words.md
- docs/reference/tags/accommodation_availability_tag/index.md
- docs/reference/tags/cache_tag/index.md
- docs/reference/tags/currency_switcher_tag/index.md
- docs/reference/tags/easol_badge_tag/index.md
- docs/reference/tags/form_tags/clear_cart/index.md
- docs/reference/tags/form_tags/create_line_item/create_line_item.md
- docs/reference/tags/form_tags/item_selections/item_selections.md
- docs/reference/tags/form_tags/remove_line_item/index.md
- docs/reference/tags/product_search/index.md
Currently clicking on a tag or filter is opening two sections in the docs navigation. 
Adding a grand_parent to tag and filter details to make position in navigation clearer.
> Complete the family

- docs/product_search/index.md
- docs/product_search/parameters.md
- docs/reference/objects/search_query.md
Adding additional examples and details on product search. I've included this as a separate section for review, to be consolidated with the existing product_search tag documentation at a later stage.
> Expand on product search

- docs/carts/cart_interactions/add_line_items.md
- docs/reference/tags/form_tags/create_line_item/create_line_item.md
- docs/troubleshooting/add_to_cart_failure.md
- docs/troubleshooting/index.md
Adds a troubleshooting page and an initial troubleshooting article for add_line_item forms.
While writing the article I realised the start_date and end_date inputs had not been included in the docs, so these have now also been added.
> Add troubleshooting page

- docs/carts/cart_interactions/add_line_items.md
- docs/reference/tags/form_tags/create_line_item/create_line_item.md
When using a `create_line_item` form it is also possible to clear the customer's cart before adding the new line items.
This adds details on how this can be done into the cart interactions guide and the quick reference area.
> Add details on clear_cart input

- docs/theme_architecture/blocks/schema/layout/index.md
- docs/theme_architecture/blocks/schema/variables/index.md
So this is following some Qs from Sam. Trying to be explicit on the use and behaviour to expect around groups. 
Not sure how best to refer to, what I've called here, "the block's Creator facing settings" / the side nav / the block settings?
> Clarity around group/layout behaviour

- docs/reference/index.md
Noticed the links here weren't working https://easol.dev/docs/reference/
Needs proper liquid tags
> Fix broken links in the reference index page

- docs/site_navigation/redirects.md
Currently creators are unable to set the homepage of their site as a template page e.g. product page, and they are unable to redirect the homepage to another page. As a workaround we use a location.replace to force the browser to load their chosen page.
Previously adding the script would create the redirect but break the site preview, therefore requiring further support from frontend to make any updates. By introducing a check that the current hostname does not contain myeasol we can enable creators to edit the block in the site admin and update the page they are redirecting to without further support from frontend enginnering.
> feat: enable creators to select redirect url

- docs/internationalisation/index.md
Minor change which adds a sentance to the docs about dates being formatting based on the users browser locale, throughout creator sites.
> docs: adding info about date formatting to internationalisation page

- docs/internationalisation/index.md
Follow up to: https://github.com/easolhq/easolhq.github.io/pull/105
Removes the link to the repo, as it's private and adds an example instead.
> docs: removing link to private repo and adding date internationalisation example

- docs/reference/tags/form_tags/clear_cart/index.md
- docs/reference/tags/form_tags/create_line_item/create_line_item.md
- docs/reference/tags/form_tags/item_selections/item_selections.md
- docs/reference/tags/form_tags/remove_line_item/index.md
This is so the frontend team can more easily target these forms. Suggestion to update docs further with examples of how we intend to use this targeting
> Update docs to reflect inclusion of  data-action attribute

- docs/theme_architecture/blocks/schema/variables/variable_types/product.md
Documents the new restriction option on the product dropdown.
To be merged after:
- https://github.com/easolhq/easol/pull/8692 (which implements the changes).
> Document new `only` option for `product` type

- index.markdown
💁 This trivial change is designed to trigger a new deployment of the Jekyll website to https://easol.dev so that @sldblog's previous changes will get deployed.
> Link to Shopify's Liquid website

- docs/theme_architecture/blocks/schema/variables/variable_types/variant.md
Documents the new restriction option on the product dropdown under `variant` attributes.
To be merged after:
- https://github.com/easolhq/easol/pull/8760
Related to:
- #113
> Document new `only_from` option for `variant` type

- docs/filters/index.md
- docs/product_search/index.md
- docs/product_search/parameters.md
- docs/reference/objects/blog_post.md
- docs/reference/objects/product/index.md
- docs/reference/objects/product/promotion.md
- docs/reference/objects/product/transfer.md
- docs/reference/objects/product/useful_info.md
- docs/reference/objects/product/variant/accommodation_variant/availabilty_day.md
- docs/theme_architecture/blocks/index.md
- docs/theme_architecture/blocks/schema/variables/index.md
About to update the docs for multi-date, tidying some things before I start:
- Remove spacing inside links, otherwise create's this:
- We already have some capitalised `Liquid`s this standardises it.
-  Missing apostrophes
- Clarify behaviour of `product.has_infinite_stock` I was drafting some methods for dates and tried to write this, realised the description here isn't as clear as it could be.
> Refactor some things

- docs/reference/objects/product/index.md
- docs/reference/objects/product/promotion.md
- docs/reference/objects/product/variant/index.md
I've updated documentation on the use of modifiers, as there was some confusion around this this morning.
I've also updated all drop methods which have been commented as deprecated in easol app, other than [product.humanized_display_amount](https://github.com/easolhq/easol/blob/4a717b109ebb5faf53a79390716c7586f227b7fb/app/drops/product_drop.rb#L266) which is deprecated, but not included in the docs at all. This gets a mention in [Alchemist](https://github.com/easolhq/alchemist-theme/blob/63b87934746172b7ac796b80597de02fd594ee13/templates/product/index.text).
Should this be included in the docs? OR Is there a way for us to confirm it's not in use anywhere at all and remove from the ProductDrop entirely?
> Update docs to reflect current implementation

- docs/experience_date_search/index.md
- docs/experience_date_search/parameters.md
- docs/product_search/index.md
- docs/reference/tags/experience_date_search_tag/index.md
Docs for the newly introduced `experience_date_search` tag.
Tag PR [here](https://github.com/easolhq/easol/pull/9096).
Search done under the hood work [here](https://github.com/easolhq/easol/pull/9064).
> Add docs for `experience_date_search` liquid tag 

- docs/reference/objects/product/experience_date.md
- docs/reference/objects/product/index.md
Follow up to [PR#124](https://github.com/easolhq/easolhq.github.io/pull/124).
~~In testing behaviour of accommodations, I've noticed we haven't implemented an `experience_dates` method on the product drop just yet. I'm suggesting it should return all upcoming and ongoing, therefore none if they're all past? Added ticket to our backlog here https://trello.com/c/LTPg7VXi/251-productdrop-responds-to-experiencedates~~ we want results to always be paginated. Removing docs to `product.experience_dates` in this PR.
> Experience date drop only 2

- docs/reference/objects/package.md
We've introduced `price_fractional` and `price_per_person_fractional` to the package drop, so this adds docs for those attributes.
> Add price attributes to package documentation

- docs/reference/objects/cart/cart_item.md
Additional empty line introduced in https://github.com/easolhq/easolhq.github.io/commit/85458a6dda6933f0f034a26680203142ea1e6b30 was causing the elements to be formatted incorrectly.
Before:
After:
> fix: ensuring correct formatting is maintained

- docs/reference/objects/package/step.md
Currently the docs list `next_step_path`, however `next_page_path` is actually what's exposed.
Personally I feel that `next_step_path` makes more sense based on the context, so ideally we'd changed what's exposed. But aware that's going to have bigger implications, as we'll need to go through and update it in the templates for any site running the existing code. Keen to hear your thoughts on if you think the value in changing that outweigh the work involved, or whether we just roll with this change to ensure the docs are correct.
> fix: resolving typo in package step drop

- docs/product_search/index.md
- docs/reference/tags/product_search/index.md
This tag is just use to search for experiences now so we need to update the docs to reflect that.
> Update `product_search` docs to remove accommodations

- docs/reference/objects/product/modifier.md
This PR follows on from [this PR](https://github.com/easolhq/easolhq.github.io/pull/139).  
We did not initially intend to have modifiers available on a per-date basis... we are now!
So updating the modifier docs to reflect this.
> Global vs date specific modifier behaviour

- docs/reference/tags/form_tags/create_line_item/create_line_item.md
We previously stated that you could only pass a single item into the `create_line_item` tag, however it is actually possible to add multiple line items in a single form, as demonstrated on [this](https://sites-ehisx.myeasol.com/products/london-wandsworth-paw-patrol) demo site for Immersive Gamebox.
To test, select multiple variant types and extras and add these to your cart.
> fix: correct docs re adding multiple items to cart

- docs/experience_slot_search/parameters.md
- docs/reference/tags/experience_slot_search_tag/index.md
Following on from PR [Experience slot search accepts array of product ids #11340](https://github.com/easolhq/easol/pull/11340), you can pass an array to this parameter. Updating the docs to reflect this.
> experience_slot_search parameter product_id accepts an array

- docs/reference/objects/product/experience_slot.md
We've added this to reflect the deposit for an experience on a specific slot date.
[The relevant platform-side PR for this change is here](https://github.com/easolhq/easol/pull/11434).
> Document `experience_slot.deposit`

- docs/reference/objects/product/variant/experience_variant/index.md
The logic for `payment_plan` changes slightly specific for experience variants when accessed through a slot, which we document here.
[The relevant platform PR for this change is here](https://github.com/easolhq/easol/pull/11449).
> Document experience_variant `payment_plan` method

- docs/reference/tags/variant_pricing/index.md
As the tin says, add long-needed documentation for the `variant_pricing` tag.
> Document the `variant_pricing` tag

- docs/experience_slot_calendar/index.md
- docs/reference/objects/experience_slot_calendar/calendar.md
- docs/reference/objects/experience_slot_calendar/date.md
- docs/reference/objects/experience_slot_calendar/index.md
- docs/reference/objects/experience_slot_calendar/slot.md
- docs/reference/objects/search_query.md
- docs/reference/tags/experience_slot_calendar_tag/index.md
This PR adds documentation for the new `experience_slot_calendar` tag.
> Slug 345 add experience slots calendar liquid tag

- docs/reference/objects/product/experience_slot.md
We've just added the ability to fetch the payment plan, if one is available, through the ExperienceSlotDrop.
To be merged after https://github.com/easolhq/easol/pull/11982.
> Document payment_plan on ExperienceSlot

- docs/reference/objects/package/item.md
Adding details on how to access the adult count and the quantity on a package item.
Can be previewed [here](http://localhost:4000/docs/reference/objects/package/item.html) when run locally.
> feat: add missing included items drops

- docs/theme_architecture/blocks/schema/variables/variable_types/experience_date.md
- docs/theme_architecture/blocks/schema/variables/variable_types/experience_slot.md
As it says on the tin! Does the 'note' make sense? All suggested changes very welcome 🙏
> Sun 34 Document experience_slot block variable

- docs/reference/objects/cart/cart_item.md
If the cart item is for an experience, this method will return it's ExperienceSlotDrop.
[Platform-side change here](https://github.com/easolhq/easol/pull/12150).
> Document CartItem#experience_slot

- docs/reference/objects/experience_slot_calendar/date.md
- docs/reference/objects/experience_slot_calendar/slot.md
- docs/reference/objects/product/experience_slot.md
As discussed in Slack - I am updating docs to reflect changes made in Nov to date.display_price. Apologies for missing this in Nov, not an excuse but seems to have been lost during the period of team changes.
I've also added some clarifying info because I am regularly confused between slot and experience_slot
> Update slot docs

- docs/pricing_and_payments/deposits.md
- docs/reference/objects/product/deposit.md
New method incoming, [branch here](https://github.com/easolhq/easol/compare/main...sun-172-expose-deposit-due-date-information-to-frontend)
I will only merge these doc changes once that code is live.
So I used the following snippet to confirm that deposit isn't actually available on extras, because how the docs are written currently suggests they might be? Clearly hasn't been an issue until now, so just making you aware, feel free to revise the docs as you see fit to reflect these changes.
And if you want to checkout the Easol branch and use this to have a click test to confirm everything is as you would expect, please do 🙏 
```
{% for product in company.products %}
<h4>product.name: {{ product.name }}</h4>
<p>product.deposit.enabled: {{ product.deposit.enabled }}</p> …
```
> Sun 172 expose deposit due date information to frontend

- docs/reference/objects/experience_slot_calendar/slot.md
- docs/reference/objects/product/experience_slot.md
- docs/reference/objects/product/variant/payment_plan.md
In most places throughout the docs nil is formatted like `nil`. I corrected it [here](https://github.com/easolhq/easolhq.github.io/pull/172/commits/c8112f97836c82596f816e5c85f401acee8460b2) as part of some new changes and thought to check/fix throughout the rest of the docs.
> formatting: converting nil to `nil` for consistency

- docs/reference/objects/product/index.md
We've added this method to the ProductDrop as a convenience method for determining if a product is an experience with >1 slot.
See https://github.com/easolhq/easol/pull/12539.
> Document `Product#is_multi_slot_experience`

- docs/reference/objects/recommendation.md
- docs/theme_architecture/templates.md
We are adding a template to sites for the
recommendation #show page. In order to
support this we added a RecommendationDrop.
This documents the new object.
PR: https://github.com/easolhq/easol/pull/12795
> Add recommendation object documentation

- _sass/custom/custom.scss
- docs/reference/objects/form/field/index.md
- docs/reference/objects/form/field/input_and_label_tags.md
- docs/reference/tags/form_tags/enquiry_form/index.md
This PR adds three pages to our docs:
- docs/reference/tags/form_tags/enquiry_form
- docs/reference/objects/form/field
- docs/reference/objects/form/field/input_and_label_tags
Wasn't sure of the best place to put input_and_label_tags, decided on this as although they are tags (could be documented under `tags`) in their own right, they are only used in the context of enquiry form fields.
> Add docs for Enquiry Form, fields, inputs & labels

- docs/reference/objects/form/field/index.md
@eballantine sorry, totally missed this when reviewing [your PR](https://github.com/easolhq/easolhq.github.io/pull/181). `field.required` returns a `boolean` rather than a `string`, so just updating to represent that.
> docs: updating `field.required` to show it returns a boolean

- docs/reference/objects/product/index.md
The ProductDrop can now return its Company so we document that here
> Adds documentation for product.company method [SCR-114]

- docs/reference/objects/package/step.md
Brings this inline with the rest of our docs.
> fix: correcting type for `package_step.step_valid?`

- docs/reference/objects/cart/cart_item.md
Documentation was previously missing for two cart item drops: is_custom_priced_package and removable?
> feat: add details for missing drops

- docs/reference/objects/page.md
This adds documentation for the new `page.params` method. 
The corresponding Rails PR can be seen here https://github.com/easolhq/easol/pull/13219
> Docs for page.params

- docs/carts/cart_interactions/add_packages.md
- docs/reference/objects/package.md
- docs/reference/objects/package/product.md
- docs/reference/objects/package/step/item.md
Here we document the changes made to packages regarding slot selection and available slots. https://github.com/easolhq/easol/pull/13133
As well as accepting adult count added here: https://github.com/easolhq/easol/pull/13240
We have recently introduced a new method on package called `items` which will replace `variants` for steps of type `experience` in order to support slot selection for multi date packages.
> Add documentation for new attributes in package and package step item

- docs/reference/objects/cart/cart_item.md
- docs/reference/objects/package_booking.md
Here are some documentation changes following the changes made in https://github.com/easolhq/easol/pull/13298. (Plus filling in some missing docs for package booking.)
> MICE-408 Docs for exposing package_booking (PackageBookingDrop) on CartItemDrop

- docs/reference/objects/menu/index.md
- docs/site_navigation/footer.md
Some Creators have wanted to be able to render a different menu depending on various page or cart attributes. This is not possible by default (nor in the footer) so we should document this so that; they realise what is possible ahead of development time, or they can more quickly debug when things are not updating.
Note; we have added a cached flag to headers to be used internally to turn off the default caching. We are not making this a standard option/feature without further consideration.
> Document behaviour of menu/footer caching

- docs/site_navigation/footer.md
The [footer is not cached](https://github.com/easolhq/easol/blob/63ac4840d61ee63f85fd9d11ba27c1dd5a3a372c/app/models/site/footer.rb#L140-L141) the same way as [the menu is cached](https://github.com/easolhq/easol/blob/2f4c0c73073393446dd05c3b5360b420dc2f5d1a/app/models/site/menu.rb#L198-L199).
Apologies we previously assumed it was.
> Fix docs re: caching the footer

- docs/reference/objects/recommendation.md
We're now exposing the terms_and_conditions_url on the recommendation object. See PR: https://github.com/easolhq/easol/pull/13473
This commits updates the docs to include that.
> Add terms_and_conditions_url to recommendation object

- docs/reference/tags/form_tags/remove_line_item/index.md
This form will only accept a `cart_item.id` and not a `variant.id` or `extra.id`. Confirmation from platform in [this thread](https://easolhq.slack.com/archives/C03HMNR7WN7/p1715176933843139).
> reflecting correct acceptance for id passed to `remove_line_item` form

- docs/reference/objects/cart/custom_data.md
- docs/reference/objects/cart/index.md
Following from this change https://github.com/easolhq/easol/pull/14163
We have swapped from exposing the internal label to the display name. I've also added a small example of how to use this, and a nod towards the visible/invisible nature of these fields.
> Update the custom data documentation

- docs/theme_architecture/blocks/schema/layout/layout_types/accordion_toggle.md
We recently updated the platform to allow `accordion_toggle` elements to be nested within `accordion`s. This PR updates the docs to reflect that.
> chore: update accordion toggle docs

- docs/reference/objects/recommendation.md
We recently add a `can_change_currency` method onto the RecommendationDrop in https://github.com/easolhq/easol/pull/14596
This PR adds the documentation for the method. The method can be used to conditionally show the currency switcher, e.g.
```
{% if recommendation.can_change_currency %}
<div class="{{ id }}__currency-switcher">
{% currency_switcher %}
</div>
{% endif %}
```
> Mice 954 expose can be booked by current user on recommendationdrop

- docs/reference/objects/adjustment/gratuity.md
- docs/reference/objects/cart/index.md
You can now retrieve information about the gratuity for an order from the cart drop. 
I've also added a new page for the gratuity drop object
> Update Docs To Reference The Gratuity Drop

- docs/reference/objects/package.md
We recently shipped [a change](https://github.com/easolhq/easol/pull/14777) to expose payment plan information on packages. 
This PR updates the docs in accordance with this change.
> feat: update package payment plan info

- docs/reference/objects/package/step/item.md
The current phrasing of the docs suggests that `available_slots_for_selection` and `requires_slot_selection` are coupled/dependent on each other.
But the actual drop code suggestions that the query associated with `available_slots_for_selection` is always executed - the only difference is that for items that don't require the customer to select from a range of available times, the maximum number of slots in the array will always be 1.
In the themes, we were previously checking that `requires_slot_selection` was true before checking slot availability on the assumption that `available_slots_for_selection` would only be executed for items requiring slot selection. If there were no slots returned, we'd set the item to sold out. But this meant that we weren't checking that slots were actually …
> refactor: update `available_slots_for_selection` documentation

- docs/experience_slot_search/index.md
- docs/product_search/index.md
- docs/reference/filters/pagination.md
- docs/reference/objects/paginate.md
- docs/reference/objects/pagination.md
- docs/theme_architecture/templates.md
I noticed the drop is `paginate` but the docs say it's `pagination`. I didn't update the name of the object itself, as unsure this makes sense to do plurally, so there's a bit of inconsistency now - but at least the docs are accurate and represent how to actually access this drop.
> fix: renaming `pagination` to `paginate` to match drop

- docs/reference/objects/package/step.md
Whether or not this package step has been configured by the creator to
auto-progress to the next step when the customer has added enough items to
their cart to satisfy its requirements.
> Document `auto_progress` on Package Step Drop

- docs/reference/tags/package_step_product_search_tag/index.md
Once we have more of the search functionality merged, we'll update this section to be more descriptive about how you can search and with what parameters - but right now you can just pass `include_organisation_products` to the tag in order to find the step if the site is in a different organisation company.
> Start the Search Params section for step product search tag

- docs/reference/tags/package_step_product_search_tag/index.md
We no longer require the passing of a step id here since we use the step which is already in the context within the tag.
See https://github.com/easolhq/easol/pull/15410/commits/31789a4b38142a6bc463bd1a2b1a0c4d51af89ef
> Update product search tag docs

- docs/reference/tags/package_step_product_search_tag/index.md
> Sold out products can be excluded from package step search results

- docs/reference/objects/experience_slot_calendar/slot.md
- docs/reference/objects/product/experience_slot.md
- docs/reference/objects/product/extra.md
- docs/reference/objects/product/index.md
- docs/reference/objects/product/modifier.md
- docs/reference/objects/product/variant/index.md
- docs/reference/tags/package_availability_tag/index.md
We've merged a change that affects how some stock methods consider 'marked as sold out'. PR: https://github.com/easolhq/easol/pull/15638
Sites use `_for_customers` stock methods which we introduced to handle timed baskets, however we're further updating them to say anything marked as sold out has 0 stock available to customers. This PR updates site docs to explain this.
> Swan 246 `remaining_stock` methods don't include things marked as sold out

- docs/reference/objects/link.md
Following up on https://github.com/easolhq/easol/pull/15683, we update the docs for the link drop.
> Update docs for url method on link

- docs/reference/objects/product/variant/fee_item_rate.md
- docs/reference/objects/product/variant/index.md
- docs/reference/objects/product/variant/tax_item_rate.md
These drops are used to represent an instance of a fee or tax rate being applied to a variant.
Both are exposed by way of the VariantDrop `fees` and `taxes` methods.
> Document FeeItemRate and TaxItemRate drops

- docs/reference/objects/product/variant/index.md
We've added this limit for performance reasons, so we've highlight it on the docs.
> Highlight the prices limit

- docs/reference/objects/recommendation.md
The `can_change_currency` option was been removed from the backend API in [this commit](https://github.com/easolhq/easol/pull/14969/commits/3471da773e8e63cc296c0a5eb134cee1641427b3), so removing it from the documentation to avoid confusion.
> Remove `can_change_currency` from Recommendation documentation

- docs/reference/tags/package_availability_tag/index.md
Once https://github.com/easolhq/easol/pull/16066 has been merged, the `package_availability` tag will support returning results for all possible adult counts. This commit updates the docs accordingly.
> Update package_availability docs for all adult counts

- docs/reference/objects/product/variant/accommodation_variant/index.md
This PR adds documentation for `AccommodationVariantDrop#min_price_of_stay_fractional`, which was introduced in https://github.com/easolhq/easol/pull/16351.
> Add docs for min_price_of_stay_fractional

- docs/reference/objects/package.md
- docs/reference/tags/package_pricing/index.md
This PR adds documentation for the following:
1. `PackageDrop#has_custom_price` (introduced in https://github.com/easolhq/easol/pull/16727).
2. `package_price` tag.
> POS-109 Expose PackageDrop#has_custom_price to theme

- docs/reference/objects/product/variant/experience_variant/index.md
- docs/reference/objects/product/variant/index.md
Context: https://linear.app/easol/issue/POS-8/fe-need-to-be-able-to-determine-if-variant-is-priced-using-the-per#comment-50f6fba5
Related: https://github.com/easolhq/easol/pull/16767
> Document `experience_variant.pricing_strategy` attribute

- docs/reference/objects/experience_slot_calendar/slot.md
- docs/reference/objects/product/experience_slot.md
We've updated these method in
https://github.com/easolhq/easol/pull/16910 so we're now updating the docs to reflect the exact formating the experience slot drop will return those.
> [POS-196] Docs reflect the correct formatting for start and end time

- docs/reference/tags/variant_pricing/index.md
We have made two changes to how this tag works this week. More simple to document is `include_fees` parameter.
Additionally, we ensure that a package step item's adopt the price of the slot that will be purchased. This is well defined for items with 'exact' or 'closest match' slot selection strateyg. For those  with a 'range' slot selection strategy, the customer will be asked to select the slot as a following interaction, so we return the cheapest of the slots they can choose from - we recommend pre-pending the price with 'From' in this case.
> Update variant_pricing tag documentation

- docs/reference/objects/product/index.md
See easol 83a7ddd4fb2c6c05a464b9f85cdf0a966ca23e01 for change to the Easol application.
There are times when the frontend want to know when 'now' is in the product's time zone, so have asked for this to be exposed. Offset in seconds is most useful due to how dates are manipulated in Liquid, where you convert to seconds first.
There are definitely more places we should be doing filtering and converting on the backend but frontend have specifically requested this, so we want to unblock them.
my test block uses:
```
---
product:
type: product
label: Product
---
{% assign offset = product.time_zone_offset %}
<p>product.time_zone_offset: {{ offset }}</p>
<p>product.time_zone_offset | divided_by 3600 (i.e. hours): {{ offset | divided_by: 3600 }}</p>
{% assign date_in_s = product.depart_on | …
```
> Document utc_offset for products
