easolhq/easolhq.github.io

docs/reference/objects/page.md
Add documentation for page variable
=> Add global page variable documentation

docs/guides/getting_started/index.md, docs/guides/index.md, docs/guides/layout/index.md, docs/reference/basics/index.md, docs/reference/filters/index.md, docs/reference/index.md, docs/reference/objects/biography.md, docs/reference/objects/company.md, docs/reference/objects/footer/index.md, docs/reference/objects/image.md, docs/reference/objects/index.md, docs/reference/objects/menu/index.md, docs/reference/objects/pagintation.md, docs/reference/objects/product/index.md, docs/reference/objects/series.md
We dont really need to specify this, the docs will just resort to
alphabetical without it
=> Remove nav_order

docs/reference/objects/product/extra.md, docs/reference/objects/product/index.md, docs/reference/objects/product/variant.md
Adding missing details on extras, has_infinite_stock and initial_stock on docs
=> Add extras and stock breakdowns to docs

Gemfile, Gemfile.lock, docs/reference/objects/accommodation/availabilty_day.md, docs/reference/objects/author.md, docs/reference/objects/blog_post.md
Mostly covering drops linked to authors/blog posts but also has availability day included
=> Update drop docs

docs/reference/objects/blog_post.md
@geoffreymm spotted a missing word but I'd already merged so making sure this doesn't get missed
=> Fix missing word in blog post docs

docs/reference/objects/color.md
This PR adds docs for the ColorDrop.
=> Drops: Add color

docs/reference/objects/company.md
This PR updates the CompanyDrop.
=> Drops: update company

docs/reference/objects/footer/footer_item.md, docs/reference/objects/footer/index.md, docs/reference/objects/menu/index.md, docs/reference/objects/menu/menu_item.md, docs/reference/objects/page.md, docs/reference/objects/request.md
This tackles the following drops:
- RequestDrop
- PageDrop
- MenuDrop
- Menu::ItemDrop
- FooterDrop
- Footer::ItemDrop
=> Menu & Footer drops

.gitignore, docs/reference/objects/product/promotion.md
This tackles the following drop:
- PromotionDrop
=> Update `promotion` drop doc

docs/reference/objects/link.md
This PR adds docs for the LinkDrop.
=> Drops: add link

docs/reference/objects/product/address.md
We've just re-order the methods alphabetically.
=> Small tweaks on `address` docs

docs/reference/objects/product/blog_post_section.md, docs/reference/objects/product/index.md
We've add methods for this drop.
There was a bug on the product drop that linked to this section, it was fixed too.
=> Complete `blog_post_section` drop doc

_config.yml
We've change the email to be `developers` and we've change the branch name to referenced `main`.
=> Change Jekyll configs

docs/reference/tags/accommodation_availability_tag/index.md, docs/reference/tags/product_search/index.md
Tag used to get the availability of a given accommodation variant.
Tag here: https://github.com/easolhq/easol/blob/main/app/tags/accommodation_availability_tag.rb
=> Add docs for `AccommodationAvailabilityTag`

docs/reference/filters/pagination.md
Adds documentation for using the pagination filter
=> Pagination filter

docs/reference/objects/product/deposit.md, docs/reference/objects/product/variant/index.md
Jorge asked me today if a deposit is calculated on price with/without promotion applied. I had asked this previously of Ian. Adding to docs for no further confusion!
=> Clarifying statement regarding deposit w/promo calculation

docs/guides/getting_started/creating_a_theme.md, docs/guides/theme_architecture/blocks/index.md, docs/guides/theme_architecture/index.md
Based on the [guidance in notion](https://www.notion.so/easol/Creating-custom-themes-theme-developer-709f4ae092de4a369a6c0e5f5204017f)
Adapted for a public audience.
=> Creating a theme guide

docs/guides/best_practices/index.md, docs/guides/cart_on_sites/index.md, docs/guides/cart_shop/index.md, docs/guides/customer_terms/index.md, docs/guides/dependencies/index.md, docs/guides/developer_tools/index.md, docs/guides/internationalisation/index.md, docs/guides/pricing_and_payments/index.md, docs/guides/product_merchandising/index.md, docs/guides/product_search/index.md, docs/guides/seo/index.md, docs/guides/site_navigation/index.md, docs/guides/site_styles/index.md, docs/guides/theme_architecture/assets/index.md, docs/guides/theme_architecture/custom_types/index.md, docs/guides/theme_architecture/directory_structure/index.md, docs/guides/theme_architecture/overview/index.md, docs/guides/theme_architecture/page_layouts/index.md, docs/guides/theme_architecture/partials/index.md, docs/guides/theme_architecture/templates/index.md, docs/guides/troubleshooting/index.md
Based on proposed layout created in Notion [here](https://www.notion.so/Proposed-Structure-6a4dd72ce4bf43fc8e2d1256b7999550)
=> Create top line file structure

docs/guides/getting_started/creating_a_theme.md, docs/guides/getting_started/easol_themes.md
This PR is covering task 
- Difference between themes (table) & overview
Remaining items we planned for [Getting started](https://trello.com/c/ahM4yIj8/308-documentation-getting-started) are: 
- Overview
- creating a theme - skeleton theme
- customise a theme - overview
- customise a theme - easol themes
But given the public facing nature of these docs, I'm not sure how much more it's appropriate to say on any of these points. 
I would personally leave it there for now for getting started; thoughts?
=> Differences between themes

docs/guides/theme_architecture/page_layouts/index.md
I wanted to include enough variety of attribute setting that 'you get the idea' whilst keeping it short. Hope this strikes the balance
=> Page layouts

docs/guides/theme_architecture/custom_types.md
Covers:
- Updating custom types
- Deleting custom types
=> Add additional details re updating custom types

docs/guides/dependencies/index.md, docs/guides/libraries/index.md
Renamed from dependencies to libraries. 
Includes:
- Included libraries and versions
- Guide to including additional libraries
=> Add libraries guide

docs/guides/internationalisation/localisation.md, docs/guides/internationalisation/translators.md
Ok so really not sure what to write here. Added some thoughts to at least get a conversation going!
=> Add guides to localisation

docs/reference/tags/form_tags/clear_cart/index.md, docs/reference/tags/form_tags/remove_line_item/index.md
This commit adds documentation for the Clear Cart tag and Remove Item Tag, including liquid tag input examples and the rendered result.
=> Documenting the Clear Cart Tag & Remove Line Item Tag

docs/filters/index.md, docs/internationalisation/translators.md, docs/tags/index.md
=> Tags and filters

docs/product_management_and_merchandising/accommodation_and_experience_products.md, docs/product_management_and_merchandising/extras.md, docs/product_management_and_merchandising/index.md, docs/product_management_and_merchandising/merchandising_fields.md, docs/product_management_and_merchandising/modifiers.md, docs/product_management_and_merchandising/overview.md, docs/product_management_and_merchandising/product_overview.md, docs/product_management_and_merchandising/series.md, docs/product_management_and_merchandising/useful_info.md, docs/product_management_and_merchandising/variants.md
So I feel I'm definitely missing some key things, and some of this is probably more the Creator/Success audience, so feel free to critique!
=> Draft all merchandising docs

docs/customer_terms/index.md
For now I haven't included details of the javascript styling workaround, I'm going to push on the outer wrapper request again next week.
=> Add customer terms breakdown

docs/site_styles/index.md
Updating the details for Site Styles where I think some of the Alchemist styling may have led to some confusion.
I've created an empty state of a site [here](https://sites-gn9ex.myeasol.com/homepage) where you can see which styling is applied without a theme.
Key updates:
- How fonts are applied
- How colours are used
=> Update site styles detail

docs/developer_tools/canvas_lint.md, docs/developer_tools/easol_palette.md
Not sure if there's more to say here?
=> Add developer tools guides

docs/best_practices/index.md
A first version of best practices to be built on in future
=> Add best practice docs

_config.yml, _sass/custom/custom.scss
Adjusting theme config for the following amendments:
- Sidebar to stick to the left
- Increased spacing below breadcrumbs
- Increased spacing below headers
=> Customise styles

index.markdown
I've taken pieces of copy from various Easol sources (website, blog etc) to pull together a homepage intro - any suggestions are very welcome!
=> Update homepage copy

docs/seo/metadata.md, docs/seo/overview.md
More considerations?
Not sure what to call /products/* pages.
=> Guide to SEO considerations for themes

_sass/custom/custom.scss, docs/reference/tags/form_tags/create_line_item/create_line_item.md
Yesterday I merged some broken links which are now causing deploying the docs to fail, this fixes those errors.
This was a mistake on my part and I'll make sure to double test before merging anything in future!
=> Deploy fixes

docs/reference/objects/product/variant/index.md
The `booking_fee_rate` was introduced in this PR https://github.com/easolhq/easol/pull/7661
=> Docs for variant.booking_fee_rate

docs/filters/index.md, docs/reference/filters/pluralize.md
This new filter allow to output the singular or plural version of a
string based on a given number.
Filter implementation: https://github.com/easolhq/easol/pull/7856.
=> Update docs to include pluralize filter 

.github/dependabot.yml
💁 These changes configure Dependabot to manage automatic updates for the Ruby dependencies of this project.
=> Dependabot: add configuration

docs/theme_architecture/blocks/schema/variables/variable_types/date.md
Basic documentation for date variable type introduced in https://github.com/easolhq/easol/pull/9104
=> Add documentation for date variable type

docs/reference/objects/product/experience_date.md, docs/reference/objects/product/index.md
What it says on the tin. Plus updating references to 'inventory' to user friendly 'stock'
=> Experience date drop only

docs/reference/tags/form_tags/create_line_item/create_line_item.md
Add docs to the feature introduce on this [PR](https://github.com/easolhq/easol/pull/9024) that allow to book a specific slot.
=> Carts on sites experience slot

docs/carts/cart_interactions/add_packages.md, docs/carts/cart_interactions/index.md, docs/reference/objects/package.md, docs/reference/objects/package/item.md, docs/theme_architecture/blocks/schema/variables/variable_types/package.md
- Add documenation for packages and package items
- Add documentation for the package add to cart form 
- Add package variable type
=> Add packages to docs

docs/reference/objects/product/extra.md
Just added this to the AddonDrop in https://github.com/easolhq/easol/pull/10341 so updating the corresponding docs
=> Add doc for extra.booking_fee_rate

docs/reference/objects/company.md
=> Document the company.booking_fee_name Method

docs/reference/objects/package/step.md
For:
* accommodated_adult_count
* min_guests_required
* max_guests_required
=> Add missing package step drop documentation

docs/reference/objects/experience_slot_calendar/slot.md, docs/reference/objects/product/experience_slot.md
Adds the descriptions to go along with the changes here in this PR: https://github.com/easolhq/easol/pull/11951
=> Sun 17 document drop changes

docs/reference/objects/product/modifier_group.md
It was not obvious where to configure this in the Creator admin.
=> Update description for modifier_group.tagline

docs/reference/objects/product/variant/accommodation_variant/availabilty_day.md
Updating the docs for AvailabilityDay#available to reflect some changes in this method's behaviour.
=> Update docs for AvailabilityDay#available [RC-184]

docs/reference/objects/recommendation.md
https://github.com/easolhq/easol/pull/12911
=> Add guest count field to recommendation object

docs/reference/tags/form_tags/enquiry_form/field/index.md, docs/reference/tags/form_tags/enquiry_form/field/input_and_label_tags.md, docs/reference/tags/form_tags/enquiry_form/index.md
Changes have not been merged yet.
Some files moved in the first commit were unreachable prior to these changes because they were not visible in the nav.
=> Document field.type method

docs/reference/objects/company.md, docs/reference/objects/organisation.md
This PR documents the new `Organisation` object and updates the `Company` documentation with the new `copmany.organisation` attribute.
=> Document Organisation

docs/reference/objects/package/price.md, docs/reference/tags/package_availability_tag/index.md
This PR adds docs for a new package availability tag and package price drop we will introduce.
=> [MICE-367] Add docs for package availability tag

docs/reference/objects/cart/custom_data.md, docs/reference/objects/cart/index.md
Update docs with cart_drop.custom_data
=> Update docs with cart_drop.custom_data

docs/reference/objects/package/step/item.md
This PR updates the docs following some recent changes in https://github.com/easolhq/easol/pull/14450
=> Mice 806 add has availability method on packagestepitemdrop

docs/reference/objects/package/step.md
Both methods introduced on this PR:
https://github.com/easolhq/easol/pull/15165.
=> Add docs for `earliest_check_in_date` and `latest_check_out_date`

docs/reference/objects/paginate.md
Oops, missed one reference in https://github.com/easolhq/easolhq.github.io/pull/215.
=> fix: renaming title of object

docs/reference/tags/package_step_product_search_tag/index.md
We'll be building out the actual search functionality soon, so will add more docs then!
=> Add initial docs for package step product search tag

docs/reference/objects/product/extra.md, docs/reference/objects/product/variant/index.md
Docs for the drop update here:
https://github.com/easolhq/easol/pull/16811
=> Add docs to `segment_position`

docs/reference/objects/package.md, docs/reference/objects/product/deposit.md
PR here: https://github.com/easolhq/easol/pull/17494
=> Update package & deposit drop docs

docs/reference/objects/experience_slot_calendar/date.md
The description isn't totally clear at the moment - have updated for clarity.
=> chore: update documentation
